### ISSUE TITLE
Configure Parse Server

### ISSUE THREAD

**Issue by aaronm1724** [triple-a-s/HotSpot#1]
Reference [Configure Parse Server Guide - iOS](https://guides.codepath.com/ios/Configuring-a-Parse-Server)

- [x] Deploy to Heroku
- [ ] Test Deployment
- [x] Setup local Parse Dashboard
- [ ] Add Parse Client to Project

**Comment by andrealin** [comment]
https://guides.codepath.org/ios/Building-Data-driven-Apps-with-Parse#use-case-post-photos-to-instagram-parse
